CREATE SCHEMA IF NOT EXISTS sw_v2;

CREATE TABLE sw_v2.transactions_master (
    ID SERIAL PRIMARY KEY,
    AMOUNT INTEGER NOT NULL,
    CATEGORY VARCHAR(255),
    SOURCE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    TYPE VARCHAR(50),
    DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER SEQUENCE sw_v2.transactions_master_id_seq RESTART WITH 1001;

CREATE TABLE sw_v2.accounts_master (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BALANCE INTEGER NOT NULL
);

ALTER SEQUENCE sw_v2.accounts_master_id_seq RESTART WITH 1;
